import json
from typing import Dict, Any, Optional
from core.dsl_schema import InvariantCheckResult, ContractClause

class LegalExplainer:
    """Explains Z3 formal counterexamples and generates suggested contract redlines."""

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
        self.api_key = api_key
        self.model_name = model_name

    def explain_counterexample(
        self,
        result: InvariantCheckResult,
        clauses: list[ContractClause],
        use_llm: bool = True
    ) -> InvariantCheckResult:
        """Enriches the InvariantCheckResult with an intuitive explanation and redline."""
        if not result.counterexample:
            return result

        # 1. Deterministic Fallback Explanation (Always works offline!)
        model_vars = result.counterexample
        ce_str = ", ".join([f"{k} = {v}" for k, v in model_vars.items()])
        
        rule_based_exp = (
            f"Mathematical Violation Detected on {result.invariant_name}.\n"
            f"Concrete Counterexample State: [{ce_str}].\n"
            f"Under this specific financial/operational scenario, all active contract clauses "
            f"({', '.join(result.involved_clauses)}) are satisfied, but the required invariant '{result.invariant_id}' is breached."
        )

        redline_template = (
            f"Recommended Amendment for {', '.join(result.involved_clauses)}: "
            f"Insert an explicit priority override clause: 'Notwithstanding anything to the contrary in this Section, "
            f"in no event shall the terms hereof supersede or violate {result.invariant_id}.'"
        )

        result.explanation = rule_based_exp
        result.suggested_redline = redline_template

        # 2. If Gemini API is available and enabled, generate nuanced legal redlines
        if use_llm and self.api_key and self.api_key != "your_gemini_api_key_here":
            try:
                from google import genai
                client = genai.Client(api_key=self.api_key)
                
                clause_texts = "\n".join([f"[{c.clause_id}]: {c.original_text}" for c in clauses if c.clause_id in result.involved_clauses])
                
                prompt = f"""You are a senior banking and financial transactions attorney.
An automated SMT formal verification solver has detected an invariant violation in a credit agreement:

Target Invariant: {result.invariant_name}
Involved Clauses:
{clause_texts}

Counterexample Model generated by SMT solver:
{json.dumps(result.counterexample, indent=2)}

Please provide:
1. A concise, 2-sentence legal explanation of why this scenario breaks the contract logic.
2. A formal contractual 'Redline / Amendment' clause that cures this loophole or eliminates the contradiction.
"""
                response = client.models.generate_content(
                    model=self.model_name,
                    contents=prompt
                )
                if response.text:
                    parts = response.text.split("2.")
                    if len(parts) == 2:
                        result.explanation = parts[0].replace("1.", "").strip()
                        result.suggested_redline = parts[1].strip()
                    else:
                        result.explanation = response.text.strip()

            except Exception as e:
                # Silently fall back to deterministic explanation so app never crashes
                print(f"[LegalExplainer] Optional LLM explanation failed, falling back to deterministic: {e}")

        return result
