import json
from typing import Dict, Any, Optional
from core.dsl_schema import InvariantCheckResult, ContractClause

class LegalExplainer:
    """Explains Z3 formal counterexamples and generates suggested contract redlines."""

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
        self.api_key = api_key
        self.model_name = model_name

    def explain_counterexample(
        self,
        result: InvariantCheckResult,
        clauses: list[ContractClause],
        use_llm: bool = True
    ) -> InvariantCheckResult:
        """Enriches the InvariantCheckResult with an intuitive explanation and redline."""
        if not result.counterexample:
            return result

        # 1. Plain-English Intuitive Fallback Explanation (Always works offline!)
        model_vars = result.counterexample
        ce_str = ", ".join([f"{k} = {v}" for k, v in model_vars.items()])
        
        if result.invariant_id == "INV-001":
            result.explanation = (
                "Section 6.01 allows the borrower to step up their leverage ratio to 4.0x EBITDA during an acquisition. "
                "However, Section 6.02 strictly forbids total debt from exceeding $30,000,000 whenever EBITDA drops below $8,000,000. "
                "When EBITDA is around $7.5M and an acquisition occurs, Section 6.01 permits borrowing over $30M, but Section 6.02 makes it illegal. "
                "Both clauses directly contradict each other!"
            )
            result.suggested_redline = (
                "Amend Section 6.01 by inserting priority language: 'Subject to the maximum debt ceiling in Section 6.02, "
                "such maximum Consolidated Leverage Ratio threshold shall automatically step up to 4.00 to 1.00...'"
            )
        elif result.invariant_id == "INV-TEMP-001":
            result.explanation = (
                "Section 8.01 guarantees the borrower an absolute 15-day cure period to fix a default before any legal action can be taken. "
                "However, Section 8.02 allows the lender to immediately accelerate and demand the entire loan back after only 5 days of non-payment. "
                "This creates a deadlock: on Day 6, the bank can seize collateral even though the borrower still has 9 days left of their cure period!"
            )
            result.suggested_redline = (
                "Amend Section 8.02: 'If any payment remains unpaid upon expiration of the mandatory 15-day Cure Period set forth in Section 8.01, "
                "the Administrative Agent may declare the entire loan immediately due and payable.'"
            )
        else:
            result.explanation = (
                f"Mathematical contradiction detected in {result.invariant_name}. Under the counterexample values [{ce_str}], "
                f"the clauses {', '.join(result.involved_clauses)} cannot hold simultaneously without violating the safety rule."
            )
            result.suggested_redline = (
                f"Insert an explicit priority override clause into {', '.join(result.involved_clauses)} specifying which clause takes precedence."
            )

        # 2. If Gemini API is available and enabled, generate nuanced legal redlines
        if use_llm and self.api_key and self.api_key != "your_gemini_api_key_here":
            try:
                from google import genai
                client = genai.Client(api_key=self.api_key)
                
                clause_texts = "\n".join([f"[{c.clause_id}]: {c.original_text}" for c in clauses if c.clause_id in result.involved_clauses])
                
                prompt = f"""You are a senior banking and financial transactions attorney.
An automated SMT formal verification solver has detected an invariant violation in a credit agreement:

Target Invariant: {result.invariant_name}
Involved Clauses:
{clause_texts}

Counterexample Model generated by SMT solver:
{json.dumps(result.counterexample, indent=2)}

Please provide:
1. A concise, 2-sentence legal explanation of why this scenario breaks the contract logic.
2. A formal contractual 'Redline / Amendment' clause that cures this loophole or eliminates the contradiction.
"""
                response = client.models.generate_content(
                    model=self.model_name,
                    contents=prompt
                )
                if response.text:
                    parts = response.text.split("2.")
                    if len(parts) == 2:
                        result.explanation = parts[0].replace("1.", "").strip()
                        result.suggested_redline = parts[1].strip()
                    else:
                        result.explanation = response.text.strip()

            except Exception as e:
                # Silently fall back to deterministic explanation so app never crashes
                print(f"[LegalExplainer] Optional LLM explanation failed, falling back to deterministic: {e}")

        return result
